"""Create or update the demo Space from the repo's app/ folder.

Hugging Face Spaces run Streamlit through the Docker SDK (sdk: docker, app_port: 8501).
The precomputed assets the app needs (metrics, plots, SHAP values, the test sample) are
copied into the Space under assets/, so the app starts fast on free CPU hardware and needs
no token. Re-running updates the Space in place.
"""

from __future__ import annotations

import logging
import shutil
import time
from pathlib import Path

from src.config import ROOT
from src.pipeline.store import Store

log = logging.getLogger(__name__)

APP_FILES = ("streamlit_app.py", "requirements.txt", "Dockerfile")
KEEP = {".gitattributes"}


def space_readme(cfg: dict) -> str:
    title = "Trade Settlement Fail Predictor" + (" (smoke)" if cfg["mode"] == "smoke" else "")
    return (
        "---\n"
        f"title: {title}\n"
        "emoji: 📉\n"
        "colorFrom: blue\n"
        "colorTo: gray\n"
        "sdk: docker\n"
        "app_port: 8501\n"
        "pinned: false\n"
        "license: mit\n"
        "short_description: Explaining LR, SVM with SMOTE, and XGBoost with SHAP\n"
        "---\n\n"
        "# Trade Settlement Fail Predictor\n\n"
        "Interactive explanations of three models that predict which trades will fail to settle: "
        "logistic regression, an SVM trained with SMOTE, and XGBoost with SHAP.\n\n"
        "**All data is synthetic**, generated by code in "
        f"[github.com/{cfg['project']['github_repo']}](https://github.com/{cfg['project']['github_repo']}). "
        "Numbers show the pipeline and the modeling, not results on real trades.\n"
    )


def build_space_dir(cfg: dict, workdir: Path, assets: dict[str, str], out: str = "space") -> list[str]:
    """Assemble the Space under workdir/out. assets maps asset name -> local path (relative
    to workdir). Returns the Space-relative file list."""
    root = Path(workdir) / out
    if root.exists():
        shutil.rmtree(root)
    (root / "assets").mkdir(parents=True)
    files = []
    for name in APP_FILES:
        shutil.copy2(ROOT / "app" / name, root / name)
        files.append(name)
    (root / "README.md").write_text(space_readme(cfg))
    files.append("README.md")
    for name, local in assets.items():
        dst = root / "assets" / name
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(Path(workdir) / local, dst)
        files.append(f"assets/{name}")
    return sorted(files)


def space_url(space_id: str) -> str:
    return f"https://huggingface.co/spaces/{space_id}"


def deploy(store: Store, workdir: Path, files: list[str], space_id: str, out: str = "space",
           wait: bool = True, timeout_s: int = 1800) -> dict:
    stale = [p for p in store.list_files() if p not in files and p not in KEEP]
    store.commit(Path(workdir) / out, files, delete=stale, message="deploy app")
    result = {"space_id": space_id, "url": space_url(space_id), "stage": "uploaded"}
    if not wait:
        return result
    from huggingface_hub import HfApi

    api = HfApi()
    deadline = time.time() + timeout_s
    time.sleep(20)
    stage = None
    while time.time() < deadline:
        runtime = api.get_space_runtime(space_id)
        stage = getattr(runtime.stage, "value", runtime.stage)
        log.info("space %s: %s", space_id, stage)
        if stage == "RUNNING":
            break
        if stage in ("BUILD_ERROR", "RUNTIME_ERROR", "CONFIG_ERROR", "NO_APP_FILE"):
            raise RuntimeError(f"Space {space_id} failed to start: {stage}. Check its logs on the Space page.")
        time.sleep(30)
    else:
        raise TimeoutError(f"Space {space_id} did not reach RUNNING within {timeout_s}s (last: {stage})")
    result["stage"] = stage
    return result
